name = "M28AI"
uid = "fnewm028quiet-v1-55b4-92b6-64398e7ge43f"
version = 291.03
copyright = "CC BY-NC-SA 4.0 Deed"
description = "Maudlin28 M28 AI designed & maintained by QUIET Team"
author = "maudlin27 & QUIET Team"
url = ""
icon = "/mods/M28AI/M28AI.jpg"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
