---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 16/11/2022 07:31
---

M28ShowUnitNames = false --Will update units to reflect the order theyve been given
M28ShowEnemyUnitNames = false --Will rename enemy units to reflect their ID and lifetime count
M28RunVeryFast = false --Game starts off at +15 speed if set to adjustable

--Detailed profiling config options
M28RunProfiling = false --If turning to true-part way through the game then also run ForkThread(M28Profiler.ProfilerActualTimePerTick); Records data on how long most functions are taking
M28ProfilingIncludePerTick = false --if M28RunProfiling is true, then this determins whether will just do the detailed log of time taken for functions, or will also include the per tick results
M28ProfilerIgnoreFirst2Seconds = false --Means logic relating to pathing generation gets ignored
M28RunMemoryProfiling = false --if this is true then every 60s will list out how much memory each file in M28 is using
M28RunGamePerformanceCheck = true --Low-overhead 10s sim-performance summary, including unit count and M28 hot-path counters
M28RunMicroStutterCheck = true --Logs individual delayed sim ticks and a rolling actual tick rate without changing synced state
M28MicroStutterTickThreshold = 0.12 --Wall-clock seconds for one sim tick before it is logged as a stutter
M28MicroStutterSummaryTicks = 50 --Emit an actual sim-tick-rate summary after this many ticks
--Simple profiling option:
M28RunSimpleProfiling = false --if this is true then will output time taken every 10s
M28DebugFunctionCalls = false --Separate from normal debug so profiling traces don't wake up every module's logs

--Centralized debug config
M28DebugGlobal = false --Enable all channels, still subject to interval and duplicate suppression
M28DebugDefaultInterval = 5 --Seconds between debug-enabled passes of the same function
M28DebugRepeatInterval = 20 --Seconds before repeating the same exact debug line for the same function
M28DebugMaxLinesPerFunctionCall = 6 --Stops one debug-enabled pass from dumping every line in the function
M28DebugFunctions = { --Exact function names to debug without enabling their whole channel
    ConsiderPriorityLandFactoryUpgrades = false,
    ConsiderPriorityAirFactoryUpgrades = false,
    GetSafeAirOrNavalHQUpgrade = false,
    UpgradeUnit = false,
    DeferAdmittedFactoryUpgrade = false,
    DecideAndBuildUnitForFactory = false,
    TryManageActiveFactoryBuildQueue = false,
    TryClaimFactoryHQUpgrade = false,
    ReleaseFactoryHQUpgrade = false,
    UpdateUpgradeTrackingOfUnit = false,
}

M28DebugACU = false
M28DebugAir = false
M28DebugBrain = false
M28DebugBuilding = false
M28DebugChat = false
M28DebugConditions = false
M28DebugEconomy = false
M28DebugEngineer = false
M28DebugEvents = false
M28DebugFactory = false
M28DebugIntel = false
M28DebugLand = false
M28DebugLogic = false
M28DebugMap = false
M28DebugMicro = false
M28DebugNavy = false
M28DebugOrders = false
M28DebugOverseer = false
M28DebugProfiler = false
M28DebugTeam = false
M28DebugUnitInfo = false
M28DebugUtilities = false
M28DebugThreatBlueprints = '' --Comma-separated blueprint ids (or *). When set, GetApproxBlueprintCombatStatThreat logs per-weapon threat outcomes for those blueprints.

M28DebugACUInterval = 2
M28DebugAirInterval = 3
M28DebugBrainInterval = 5
M28DebugBuildingInterval = 5
M28DebugChatInterval = 10
M28DebugConditionsInterval = 5
M28DebugEconomyInterval = 2
M28DebugEngineerInterval = 3
M28DebugEventsInterval = 5
M28DebugFactoryInterval = 2
M28DebugIntelInterval = 4
M28DebugLandInterval = 2
M28DebugLogicInterval = 5
M28DebugMapInterval = 6
M28DebugMicroInterval = 2
M28DebugNavyInterval = 3
M28DebugOrdersInterval = 5
M28DebugOverseerInterval = 5
M28DebugProfilerInterval = 10
M28DebugTeamInterval = 3
M28DebugUnitInfoInterval = 8
M28DebugUtilitiesInterval = 8
